import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BreakingNews from '../BreakingNews/BreakingNews.js'
import HotTopics from '../components/HotTopics/HotTopics.js'
import Trending from '../components/Trending/Trending'
import Nav from "../components/navigation/Nav"


export default function Home() {
  return (
    <div >
      <Head>
        <title>News-Express</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
        @import
         url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');
        </style>
      </Head>
      <Nav />
      <BreakingNews />
      <div style={{display:"flex"}}>
        <HotTopics />
        <Trending/>
    </div>
      
    </div>
  )
}
